### ISSUE TITLE
select fields with , fail

### ISSUE THREAD

**Issue by vituxre** [kylefarris/node-querybuilder#25]
When i use `.select('field1, if(field2=1, true, false) as field3')` this fails with "Cannot read property 'substring' of undefined", if i do the same but defining fields as array `.select(['field1', 'if(field2=1, true, false) as field3'])` then everything works good, would be nice to fix this :)
same happens if select includes `concat(field1, ' ', field2)`

**Comment by kylefarris** [comment]
@vituxre Could you show me a complete example of a query you're trying to run? Please show the Javascript node-querybuilder code you're doing as well as the expected SQL string it should generate.

**Comment by vituxre** [comment]
controller:
![screenshot 2018-06-04 15 55 27](https://user-images.githubusercontent.com/2478416/40924762-fd30cb86-680f-11e8-90dd-27d3d248c9cb.png)
helpers/qb:
![screenshot 2018-06-04 15 55 47](https://user-images.githubusercontent.com/2478416/40924763-fd690ef6-680f-11e8-80af-969e03c95ff5.png)
opening url /
![screenshot 2018-06-04 15 56 43](https://user-images.githubusercontent.com/2478416/40924765-fd8d11ac-680f-11e8-9a2d-f272f5239fdf.png)
opening url /2
![screenshot 2018-06-04 15 56 54](https://user-images.githubusercontent.com/2478416/40924766-fda493b8-680f-11e8-8f42-55d10a1419f7.png)
table:
![screenshot 2018-06-04 15 58 57](https://user-images.githubusercontent.com/2478416/40924873-393a4850-6810-11e8-86af-a6878fc183a0.png)

**Comment by kylefarris** [comment]
@vituxre I haven't forgotten--just been busy with work. I'll take a look now.

**Comment by kylefarris** [comment]
@vixture This is actually, at least to some degree, the expected behavior. It would be out of the scope of this project for it to be able to parse functions or logic like this. In the README it states:

> You can optionally choose not to have the driver auto-escape the fieldnames (dangerous, but useful if you a utilize function in your select statement, for instance):

```SQL
// SELECT CONCAT(first_name,' ',last_name) AS `full_name`
qb.select('CONCAT(first_name,' ',last_name) AS `full_name`', false);
```

You should be passing in `false` as the second parameter when providing functions, switch/case, ternaries, etc...

On the other hand, the app should not necessarily be failing _the way that it is_... I really should add some kind of try/catch in that area to throw a more useful/appropriate error message. So, I'll see what I can do on that front.

Hope that helps! And thanks for bringing this to my attention! 👍

**Comment by vituxre** [comment]
Thank you, yes that helps :)
