### ISSUE TITLE
After delete query, select does not work

### ISSUE THREAD

**Issue by vituxre** [kylefarris/node-querybuilder#26]
![screenshot 2018-06-11 14 04 12](https://user-images.githubusercontent.com/2478416/41233127-5603606e-6d80-11e8-8de3-20bed5285954.png)

db table is empty just has the "column_1" (works the same if table has contents)

response from the first url is normal
![screenshot 2018-06-11 14 05 36](https://user-images.githubusercontent.com/2478416/41233188-8d348568-6d80-11e8-87cd-9bf0ca5ad690.png)

but from the second after delete, app fails (records get deleted, just the select afterwards fails)
<img width="1133" alt="screenshot 2018-06-11 14 05 10" src="https://user-images.githubusercontent.com/2478416/41233195-953a6cc8-6d80-11e8-91d3-0b123541fd39.png">

**Comment by kylefarris** [comment]
Apparently I didn't have any tests to check for that scenario. I've been using this library for years in production and haven't experienced this issue--it may only happen after a delete. I'm investigating now. Fix should be out soon.

**Comment by kylefarris** [comment]
This is a particularly peculiar bug. It does seems to only be happening after delete statements and I'm still trying to figure out exactly what's happening to cause it.

**Comment by kylefarris** [comment]
I think this is going to take some bigger fixing at a fundamental level. I'm working on a new version which is going to sorta re-write the code a little bit. The API should stay basically the same, though. There's definitely some kind of reference errors that I can't track down and it may be due to the way the code is written.

So, expect a patch in version 3.

**Comment by kylefarris** [comment]
This is officially fixed in the v2 branch. Beta should be out soon.
