### ISSUE TITLE
Deleting using 'where object' with array value ignores other properties

### ISSUE THREAD

**Issue by Flamenco** [kylefarris/node-querybuilder#28]
Expected behavior
All properties should use 'AND'

```js
qb.delete('tags', {songId: [300], tagName: oldTag}, (err, res) => {})
```
This query results in
```sql
DELETE FROM `tags` WHERE `songId` IN (300)
```

Workaround: Re-add ignored fields.
```js
qb.where({tagName: oldTag}).delete('tags', {songId: [300], tagName: oldTag}, (err, res) => {})
```
This query results in
```sql
DELETE FROM `tags` WHERE `tagName` = 'test1' AND `songId` IN (300)
```

This applies to at least this 'delete use-case', if not more.

**Comment by Flamenco** [comment]
@kylefarris My example is a pruned down version that isolates the issue.  My actual query had hundreds of items in the array.

**Comment by kylefarris** [comment]
@Flamenco Oh, I'm sure. Looks like a totally valid issue, I just never thought of that particular case when writing the tests. I'm deep into writing version 2 of the module. The fix for this will be in that release. I'm hoping to have it out in the next few weeks or so. I'm glad you have workaround for now.

Thanks for your bug report and input!

**Comment by kylefarris** [comment]
This is officially fixed in the v2 branch. Beta should be out soon.
