### ISSUE TITLE
Allow Date objects as values.

### ISSUE THREAD

**Issue by malles** [kylefarris/node-querybuilder#3]
[This check](https://github.com/kylefarris/node-querybuilder/blob/master/drivers/mysql/query_builder.js#L1181) makes it impossible to pass Date objects as values.

```
    if ((typeof v).match(/^(number|string|boolean)$/) === null && v !== null) {
           throw new Error("set(): Invalid value provided! (provided: " + v + " (type: " + (typeof v) + ")");
    }
```

While when bypassed, the query is executed fine, and the dates are inserted as expected.
Is this an acceptable solution?:

```
    if ((typeof v).match(/^(number|string|boolean)$/) === null && v !== null && v.getFullYear === undefined) {
           throw new Error("set(): Invalid value provided! (provided: " + v + " (type: " + (typeof v) + ")");
    }
```

**Comment by kylefarris** [comment]
Sorry for the late response, but, no, this wouldn't be a great way to validate a date coming in as a value since any object could have a `getFullYear` method. I could make an argument that all dates should always be passed in as strings and not Date objects (MySQL doesn't support this and will just run the default `.toString()` method on it). If you convert to a string yourself, you'll have better control over format, timezone, etc... In any case... the proper way to check it would be to see if the value is an _instance_ of a Date object. 

So, the following should work fine:

```javascript
if ((typeof v).match(/^(number|string|boolean)$/) === null && v !== null && !(v instanceof Date)) {
    throw new Error("set(): Invalid value provided! (provided: " + v + " (type: " + (typeof v) + ")");
}
```

However, what I'll probably do in the code is coerce any dates into strings and the run it through the original check like so...

```javascript
if (v instanceof Date) v = v.toString();
if (v !== null && (typeof v).match(/^(number|string|boolean)$/) === null) {
    throw new Error("set(): Invalid value provided! (provided: " + v + " (type: " + (typeof v) + ")");
}
```
