### ISSUE TITLE
[v2] Standardize insert_id

### ISSUE THREAD

**Issue by Flamenco** [kylefarris/node-querybuilder#41]
The docs state this value should be insert_id, but MySql driver returns insertId.

Since this is such a common item to retrieve, I think the drivers should all map to the same field name.

**Comment by kylefarris** [comment]
I agree, this should definitely be consistent. I'm looking at the code, though, and it would seem that it already *should* be returning it as `insert_id`. I'll investigate further.

**Comment by kylefarris** [comment]
It looks like it's returning both `insertId` and `insert_id` which actually makes sense because I'm just merging in the `node-querybuilder` standardized fields (`insert_id`, `affected_rows`, and `changed_rows`) into the normal MySQL driver's response object.

I think this allows for the best of both worlds--maximum flexibility as well a standard API for all drivers.

Are you not getting the `insert_id` along with the `insertId` like I am?

**Comment by Flamenco** [comment]
I did not see that it returned both, so I will double check.  If I can rely on insert_id, affected_rows, and changed_rows to be consistent across DB's then that's GREAT!
